[".intellimacs"]
type = "git-repo"
url = "https://github.com/mariolopjr/intellimacs"
refreshPeriod = "168h"
[".asdf"]
type = "archive"
url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.13.1.tar.gz"
exact = true
stripComponents = 1
