dictionaries = ["en_us"]
words = [
    "CLI",
    "Esc",
    "OSC",
    "autocmd",
    "autocommands",
    "bngarren",
    "bufnr",
    "catppuccin",
    "cfile",
    "checkboxes",
    "checkhealth",
    "chezmoi",
    "chezmoidata",
    "chickensoft",
    "clangd",
    "csharpier",
    "dragonstone",
    "folke",
    "frontmatter",
    "gfm",
    "godottest",
    "gopls",
    "gotest",
    "gotmpl",
    "hlsearch",
    "jsonls",
    "keymaps",
    "lazypath",
    "lifecycle",
    "lnum",
    "macchiato",
    "matchit",
    "matchparen",
    "mise",
    "modelines",
    "nas",
    "neotest",
    "neovim",
    "neovim's",
    "netrw",
    "nixd",
    "nohlsearch",
    "noremap",
    "nvim",
    "qlab",
    "rtp",
    "runtimepath",
    "shiftwidth",
    "signcolumn",
    "stylua",
    "tabline",
    "tabstop",
    "targaryen",
    "tmpl",
    "tohtml",
    "tpope",
    "wezterm",
    "winterfell",
    "yamlls",
    "zettelkasten",
    "zls",
]
ignore_paths = [
    ".github/workflows/**",
    "dot_config/private_fish/fish_plugins",
    "dot_config/private_fish/completions/**",
]
ignore_patterns = ['\[[A-Za-z]\]\w*']
