name: install

on:
  pull_request:
  schedule:
    - cron: "0 13 * * 6"

jobs:
  install_dots:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Check versions of pre-installed software/system
        run: |
          brew --version
          sw_vers
      - name: Install dotfiles
        run: |
          brew install chezmoi
          chezmoi init --apply mariolopjr
      - name: Check installed versions
        run: |
          brew list --versions
          brew list --cask --versions
          mas list
